[2025-04-22T22:51:13.327+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T22:51:13.352+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_files_projetos_grupo_1.upload_projeto_2439_oceanpact manual__2025-04-22T22:51:06.799963+00:00 [queued]>
[2025-04-22T22:51:13.364+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_files_projetos_grupo_1.upload_projeto_2439_oceanpact manual__2025-04-22T22:51:06.799963+00:00 [queued]>
[2025-04-22T22:51:13.367+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-22T22:51:13.386+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_projeto_2439_oceanpact> on 2025-04-22 22:51:06.799963+00:00
[2025-04-22T22:51:13.394+0000] {standard_task_runner.py:72} INFO - Started process 1273 to run task
[2025-04-22T22:51:13.399+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'upload_files_projetos_grupo_1', 'upload_projeto_2439_oceanpact', 'manual__2025-04-22T22:51:06.799963+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dag_grupo-01.py', '--cfg-path', '/tmp/tmp7c6mkdu7']
[2025-04-22T22:51:13.404+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask upload_projeto_2439_oceanpact
[2025-04-22T22:51:13.463+0000] {task_command.py:467} INFO - Running <TaskInstance: upload_files_projetos_grupo_1.upload_projeto_2439_oceanpact manual__2025-04-22T22:51:06.799963+00:00 [running]> on host e50052774237
[2025-04-22T22:51:13.546+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arthur.lopes' AIRFLOW_CTX_DAG_ID='upload_files_projetos_grupo_1' AIRFLOW_CTX_TASK_ID='upload_projeto_2439_oceanpact' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T22:51:06.799963+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T22:51:06.799963+00:00'
[2025-04-22T22:51:13.549+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T22:51:13.718+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/dag_grupo-01.py", line 84, in upload_files_2439_oceanpact
    upload_to_blob(
  File "/opt/airflow/dags/dag_grupo-01.py", line 24, in upload_to_blob
    raise e
  File "/opt/airflow/dags/dag_grupo-01.py", line 18, in upload_to_blob
    with open(local_file_path,"rb") as data:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dados/01. LD e CR/2439 - OCEANPACT/01. LISTA DE DOCUMENTOS/LD-2439-PE-CBA-PLN-GER-001.xlsx'
[2025-04-22T22:51:13.740+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=upload_files_projetos_grupo_1, task_id=upload_projeto_2439_oceanpact, run_id=manual__2025-04-22T22:51:06.799963+00:00, execution_date=20250422T225106, start_date=20250422T225113, end_date=20250422T225113
[2025-04-22T22:51:13.774+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T22:51:13.776+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 38 for task upload_projeto_2439_oceanpact ([Errno 2] No such file or directory: '/opt/airflow/dados/01. LD e CR/2439 - OCEANPACT/01. LISTA DE DOCUMENTOS/LD-2439-PE-CBA-PLN-GER-001.xlsx'; 1273)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/dag_grupo-01.py", line 84, in upload_files_2439_oceanpact
    upload_to_blob(
  File "/opt/airflow/dags/dag_grupo-01.py", line 24, in upload_to_blob
    raise e
  File "/opt/airflow/dags/dag_grupo-01.py", line 18, in upload_to_blob
    with open(local_file_path,"rb") as data:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dados/01. LD e CR/2439 - OCEANPACT/01. LISTA DE DOCUMENTOS/LD-2439-PE-CBA-PLN-GER-001.xlsx'
[2025-04-22T22:51:13.815+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-22T22:51:13.845+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-22T22:51:13.852+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
