[2025-04-20T07:51:47.135+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-20T07:51:47.151+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api-eclick.api-eclick scheduled__2025-04-18T17:00:00+00:00 [queued]>
[2025-04-20T07:51:47.158+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api-eclick.api-eclick scheduled__2025-04-18T17:00:00+00:00 [queued]>
[2025-04-20T07:51:47.159+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-20T07:51:47.173+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): api-eclick> on 2025-04-18 17:00:00+00:00
[2025-04-20T07:51:47.179+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=108) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-20T07:51:47.181+0000] {standard_task_runner.py:72} INFO - Started process 110 to run task
[2025-04-20T07:51:47.181+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api-eclick', 'api-eclick', 'scheduled__2025-04-18T17:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_projeto_api-eclick.py', '--cfg-path', '/tmp/tmpa63punr_']
[2025-04-20T07:51:47.183+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask api-eclick
[2025-04-20T07:51:47.227+0000] {task_command.py:467} INFO - Running <TaskInstance: api-eclick.api-eclick scheduled__2025-04-18T17:00:00+00:00 [running]> on host b23a63934d1d
[2025-04-20T07:54:02.623+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arthur.lopes' AIRFLOW_CTX_DAG_ID='api-eclick' AIRFLOW_CTX_TASK_ID='api-eclick' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-18T17:00:00+00:00'
[2025-04-20T07:54:02.625+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-20T07:54:02.649+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_projeto_api-eclick.py", line 21, in acesso_url
    response = requests.get(odata_url, auth=HTTPBasicAuth(credenciais.usuario, credenciais.senha))
                                                          ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'credenciais' has no attribute 'usuario'
[2025-04-20T07:54:02.665+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=api-eclick, task_id=api-eclick, run_id=scheduled__2025-04-18T17:00:00+00:00, execution_date=20250418T170000, start_date=20250420T075147, end_date=20250420T075402
[2025-04-20T07:54:02.692+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-20T07:54:02.693+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task api-eclick (module 'credenciais' has no attribute 'usuario'; 110)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_projeto_api-eclick.py", line 21, in acesso_url
    response = requests.get(odata_url, auth=HTTPBasicAuth(credenciais.usuario, credenciais.senha))
                                                          ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'credenciais' has no attribute 'usuario'
[2025-04-20T07:54:02.723+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-20T07:54:02.736+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T07:54:02.741+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
