[2025-04-23T18:34:15.142+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T18:34:15.167+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestao-blobstorage-azure.ingestao_azure-2446 scheduled__2025-04-22T17:00:00+00:00 [queued]>
[2025-04-23T18:34:15.184+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestao-blobstorage-azure.ingestao_azure-2446 scheduled__2025-04-22T17:00:00+00:00 [queued]>
[2025-04-23T18:34:15.192+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-23T18:34:15.212+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingestao_azure-2446> on 2025-04-22 17:00:00+00:00
[2025-04-23T18:34:15.222+0000] {standard_task_runner.py:72} INFO - Started process 2588 to run task
[2025-04-23T18:34:15.225+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ingestao-blobstorage-azure', 'ingestao_azure-2446', 'scheduled__2025-04-22T17:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/ingestao-blobstorage-azure.py', '--cfg-path', '/tmp/tmp2ix9e7ck']
[2025-04-23T18:34:15.231+0000] {standard_task_runner.py:105} INFO - Job 84: Subtask ingestao_azure-2446
[2025-04-23T18:34:15.291+0000] {task_command.py:467} INFO - Running <TaskInstance: ingestao-blobstorage-azure.ingestao_azure-2446 scheduled__2025-04-22T17:00:00+00:00 [running]> on host e50052774237
[2025-04-23T18:34:15.366+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestao-blobstorage-azure' AIRFLOW_CTX_TASK_ID='ingestao_azure-2446' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T17:00:00+00:00'
[2025-04-23T18:34:15.372+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T18:34:25.561+0000] {logging_mixin.py:190} INFO - Erro ao enviar o arquivo 'LD-2446-PE-CAR-PLN-GRC-001-R0.xlsx': [Errno 112] Host is down: '/opt/***/dados/01. LD e CR/2446 - BRASFELS/01. LISTA DE DOCUMENTOS/LD-2446-PE-CAR-PLN-GER-001-R0.xlsx'
[2025-04-23T18:34:25.570+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 45, in upload_files_brasfels
    upload_to_blob(
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 25, in upload_to_blob
    raise e
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 18, in upload_to_blob
    with open(local_file_path, "rb") as data:
OSError: [Errno 112] Host is down: '/opt/airflow/dados/01. LD e CR/2446 - BRASFELS/01. LISTA DE DOCUMENTOS/LD-2446-PE-CAR-PLN-GER-001-R0.xlsx'
[2025-04-23T18:34:25.584+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=ingestao-blobstorage-azure, task_id=ingestao_azure-2446, run_id=scheduled__2025-04-22T17:00:00+00:00, execution_date=20250422T170000, start_date=20250423T183415, end_date=20250423T183425
[2025-04-23T18:34:25.603+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T18:34:25.604+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 84 for task ingestao_azure-2446 ([Errno 112] Host is down: '/opt/airflow/dados/01. LD e CR/2446 - BRASFELS/01. LISTA DE DOCUMENTOS/LD-2446-PE-CAR-PLN-GER-001-R0.xlsx'; 2588)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 45, in upload_files_brasfels
    upload_to_blob(
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 25, in upload_to_blob
    raise e
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 18, in upload_to_blob
    with open(local_file_path, "rb") as data:
OSError: [Errno 112] Host is down: '/opt/airflow/dados/01. LD e CR/2446 - BRASFELS/01. LISTA DE DOCUMENTOS/LD-2446-PE-CAR-PLN-GER-001-R0.xlsx'
[2025-04-23T18:34:25.646+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-23T18:34:25.665+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T18:34:25.684+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
